config add web middleware
ome/omero-py pull request #280
Opened 2021-03-03 23:06 UTC by will-moore

See https://github.com/ome/omero-web/pull/260

With an update to the default `omero.web.middleware` as in the PR above,
if the user has previously updated their config then the values will be stored in the `etc/grid/config.xml` and
the new default will be ignored.
This PR aims to update the `omero.web.middleware` config in the same way as the above PR.

NB: last commit of the PR above changes the default `omero.web.middleware` setting so that it is simpler
for this PR to update in the same way (simply append a single class, instead of update multiple classes in the list).
This allows us to simplify the update and reduce the amount of settings that are hard-coded in `config.py`.

NB: With this PR, it will be important to update `omero-web` at the same time as `omero-py`, since this PR depends the `omeroweb.middleware.CustomHeadersMiddleware` class added in 
https://github.com/ome/omero-web/pull/260.

It *might* be possible to check for the presence of `omeroweb.middleware.CustomHeadersMiddleware` and not update `config.xml` if it failed to import. However, we would also have to avoid bumping the version to `5.2.0` if no update was made, otherwise no future attempt would be made to update.
Or, we could ignore the version number and simply try adding `omeroweb.middleware.CustomHeadersMiddleware` if it isn't already in the config and the class can be imported?

2021-03-04 10:55 UTC, joshmoore requested changes
A few suggestions for modification. Additionally, this solves the specific issue, but doesn't solve the overall design bug. That's certainly a trade-off we can make, but just to be clear.

2021-03-04 10:55 UTC, joshmoore commented on src/omero/config.py
> +                        "Failed to import"
Does this mean the user should upgrade omero-web? Worth saying so?

2021-03-04 10:55 UTC, joshmoore commented on src/omero/config.py
> +            if version == "5.1.0" and v is not None:
This block is only really needed `if x == omero.web.middleware`, right?

2021-03-04 10:55 UTC, joshmoore commented on src/omero/config.py
> +                            val = x.get("value", "")
Should the default be `[]` or `{}`? Doesn't `json.loads("")` throw?

2021-03-04 11:19 UTC, will-moore commented on src/omero/config.py
> +            if version == "5.1.0" and v is not None:
We don't have access to `x` at this point. `v` is a list of properties and we need to update the value of `omero.web.middleware` and the `omero.config.version`.

2021-03-04 11:25 UTC, will-moore commented on src/omero/config.py
> +                            val = x.get("value", "")
fixed in d4e16be

2021-03-04 11:25 UTC, will-moore commented on src/omero/config.py
> +                        "Failed to import"
fixed in d4e16be

2021-03-04 11:29 UTC, joshmoore commented on src/omero/config.py
> +            if version == "5.1.0" and v is not None:
Sure, but the for loop over v could be moved up to this point, no?

2021-03-04 11:30 UTC, joshmoore submitted a review, later dismissed

2021-03-04 11:39 UTC, will-moore commented
@joshmoore I could maybe do a better fix by creating a `INSTALLED_MIDDLEWARE` and `ADDITIONAL_MIDDLEWARE` in https://github.com/ome/omero-web/pull/260 (just as we have for  `omero.web.apps` with `INSTALLED_APPS` and `ADDITIONAL_APPS`). Then use this `config.py` update to only leave user-configured middleware in the `omero.web.middleware` (ADDITIONAL_MIDDLEWARE) list.
I might give it a try and see how it looks...
Don't know if/when we might want to apply this to other configs. There's not many that we are likely to update.

2021-03-04 11:52 UTC, joshmoore commented
> Don't know if/when we might want to apply this to other configs.

Are there others where we are copying a default?

2021-03-04 12:19 UTC, will-moore commented
I could list them. Looking for where we use `json.loads` and the default isn't empty:

```
"omero.web.caches": '{"default": {"BACKEND":' ' "django.core.cache.backends.dummy.DummyCache"}}'
"omero.web.server_list": '[["%s", 4064, "omero"]]' % CUSTOM_HOST
"omero.web.open_with": '[["Image viewer", "webgateway", {"supported_objects": ["image"],"script_url": "webclient/javascript/ome.openwith_viewer.js"}]]'
"omero.web.ui.top_links": (Data, History, Help)
"omero.web.ui.metadata_panes": (tag, map, table, file, comment, rating, other)
"omero.web.ui.right_plugins":  (Aquisition, Preview)
```

I don't *expect* many of those defaults to change, or for users to have them configured. Except maybe `top_links` and `open_with`. BUT, if we only allow users to ADD to the defaults, then they can't remove items from defaults. E.g. remove `metadata_panes`.
The same applies to `omero.web.middleware`. If someone has already removed an item from the default settings, then putting all the defaults into a non-editable list would add it back. So we can't support `remove` of defaults AND auto update of defaults.
I think I'll try the separation of `omero.web.middleware` into 'installed' and 'additional' lists, and we can see what that looks like. Then we can decide if we want to do the same with `open_with` and/or `top_links`.

2021-03-04 13:07 UTC, will-moore commented
With https://github.com/ome/omero-web/pull/260/commits/70d22293e45a76d2fd47ab56f48bc41f61688719 and the last commits above, the user settings are now distinct from the default middleware.

2021-03-05 12:05 UTC, joshmoore reviewed
Testing locally:
 * In a new environment, ran `append` and the full list was cached.
 * Updated omero-py and ran get, the old version was shown.
 * Ran with `DEBUG=1` and could see the message telling me to upgrade.
 * Updated omero-web and was only shown the properties I had set.

Questions inline.

2021-03-05 12:05 UTC, joshmoore commented on src/omero/config.py
> +                        "Failed to import"
This only gets printed if the user sets `DEBUG=1 ...` which seems pretty unlikely.

2021-03-05 12:05 UTC, joshmoore commented on src/omero/config.py
> +            "django.middleware.common.BrokenLinkEmailsMiddleware",
So there's no way to disable this middleware, right? Are there any cases you can think of where that would be necessary?

2021-03-05 15:27 UTC, joshmoore commented
@sbesson was kind enough to scour the history to find https://github.com/ome/openmicroscopy/pull/2030#issuecomment-33578012 -- pasting it here for reference.

2021-03-08 07:07 UTC, will-moore commented on src/omero/config.py
> +            if version == "5.1.0" and v is not None:
I'm sorry, I'm not seeing it. The loop over v starts right after I check if `v is not None`.

2021-03-08 07:10 UTC, will-moore commented on src/omero/config.py
> +            "django.middleware.common.BrokenLinkEmailsMiddleware",
No, I can't think of any.

2021-03-08 07:25 UTC, will-moore commented
I don't think we're going to be able to apply the same approach to the other settings lists above.
For the UI settings (and open_with), it's possible a user will have configured them to remove one or more default items.
For `web.caches`, this isn't a list, so if it's been configured it will likely be `set` rather than `append` to default.
I guess for `server_list`, we might want to change the one default option at some point. But I think we could leave any upgrade path in config.py till it's needed.

2021-03-08 13:01 UTC, joshmoore commented on src/omero/config.py
> +            if version == "5.1.0" and v is not None:
No worries. It's a super minor optimization and this isn't critical code.

2021-06-16 10:57 UTC, will-moore commented
With https://github.com/ome/omero-web/pull/260 closed for now, don't need this currently. Closing...

2021-06-16 10:57 UTC, closed without merging