Numpy pixels type
ome/omero-py pull request #387
Opened 2023-12-13 15:15 UTC by will-moore

Currently, if we want to find the numpy pixels type for an Image, we have to duplicated code from the BlitzGateway, as in https://github.com/ome/omero-cli-zarr/pull/157/files

This PR aims to avoid that duplication by providing `PixelsWrapper.get_numpy_pixels_type()`

2025-03-14 14:16 UTC, sbesson requested changes

2025-03-14 14:16 UTC, sbesson commented on src/omero/gateway/__init__.py
> +                    (planeY*planeX), pixelTypes[pixelType])
Could we simplify this further by using `numpy.dtype(numpyType).char`?

2025-03-14 14:16 UTC, sbesson commented on src/omero/gateway/__init__.py
> +    def get_numpy_pixels_type(self):
This could use a docstring. Additionally, should this be simplified as `get_numpy_type()` ?

2025-03-14 14:16 UTC, sbesson commented on src/omero/gateway/__init__.py
> +OMERO_NUMPY_DTYPES = {
I would call this `OMERO_NUMPY_TYPES` to avoid the `type` vs `dtype` confusion

2025-04-08 09:43 UTC, sbesson commented
@will-moore would you consider this is still in scope for the next minor release of OMERO.py? If so, do you have a timeline for addressing the review comments?

2025-04-08 10:56 UTC, will-moore commented on src/omero/gateway/__init__.py
> +    def get_numpy_pixels_type(self):
I went for `get_numpy_dtype()` here since `dtype` is what they're called for numpy.

2025-04-08 10:57 UTC, will-moore commented
Thanks for the ping @sbesson - pushed some fixes.

2025-04-08 11:10 UTC, sbesson commented on src/omero/gateway/__init__.py
> +        return OMERO_NUMPY_TYPES[pixels_type]
Should this wrap `return dtype(OMERO_NUMPY_TYPES[pixels_type])` as per the new method name?

2025-04-08 11:10 UTC, sbesson commented on src/omero/gateway/__init__.py
> +        numpyType = self.get_numpy_pixels_type()
The method name has been changed in the last commit

2025-04-08 11:22 UTC, will-moore commented on src/omero/gateway/__init__.py
> +        return OMERO_NUMPY_TYPES[pixels_type]
No, I'll rename again! Kinda confusing how `np.int8` isn't a dtype but a class. 4600d63

2025-04-08 14:19 UTC, sbesson approved these changes
Retested the last few commits using the OMERO.py gateway as a client against various images of different dimensionalities. In all cases, `PixelsWrapper.get_numpy_type()` returned the expected scalar type and consumer methods like `getTiles` kept working as expected.

Waiting for a round of successful CI builds including this PR before merging this. As discussed in the weekly OME meeting, the proposal is to create a new minor release of OMERO.py focused on Numpy improvements immediately after

2025-04-08 14:55 UTC, merged