added `repr_html` method for `_ImageWrapper`
ome/omero-py pull request #394
Opened 2024-01-30 14:46 UTC by jo-mueller

Fixes #393 

## Description

This PR overwrites the `repr_html` for the `_imageWrapper` class to show a html overview object in Jupyter Notebooks whenever an `ImageWrapper` object is sown in a cell. In essence, it creates an html object and fills it with some essential information about the image. Currently displayed:

- Image ID
- Project ID
- Description
- Image Name
- Image dimensions (TCZYX)
- Voxel dimensions (currently output with long names (e.g. `MICROMETER` - there is probably a way to add the units as µm or whatever it is set to).
- Channel names

Let me know what else you would consider relevant or added/changed in the displayed object. I am by no means an html expert, so there is certainly some room for improvement there :)

2024-01-31 16:17 UTC, will-moore commented
This looks good:

![Screenshot 2024-01-31 at 15 51 51](https://github.com/ome/omero-py/assets/900055/04b600f2-c8d7-488f-b7e1-f8156022e051)

You're missing Dataset info. You can get a Dataset with `self.getParent()` although it might return `None` if more than one (or orphaned). Also `getProject()` could return None so you need to handle that possibility.

I had a go with this...

```

        def obj_html(obj, otype):
            return f"""<tr>
                    <td><b>{otype}</b></td>
                    <td class=text-right>{obj.id if obj else ""}</td>
                    <td class=text-right>{obj.name if obj else ""}</td>
                    </tr>
                """

        # create a sub-table for image information
        table_imageinfo = f"""
        <table>
            <tr><th></th><th>ID</th><th>Name</th></tr>
            {obj_html(self, 'Image')}
            {obj_html(self.getParent(), 'Dataset')}
            {obj_html(self.getProject(), 'Project')}
        </table>
        """
```

![Screenshot 2024-01-31 at 16 17 05](https://github.com/ome/omero-py/assets/900055/7a80b5c9-1ce0-4920-8316-a7e5c32c47ad)

2024-01-31 16:20 UTC, will-moore commented
cc @pwalczysko @jburel - Any suggestions here?

2024-01-31 16:30 UTC, pwalczysko commented
> cc @pwalczysko @jburel - Any suggestions here?

What about pixel type and ROIs (number of ROIs) ?

2024-01-31 17:39 UTC, jo-mueller commented
@will-moore I think it'll make sense to reduce the precision on the displayed voxel dimensions. Should be an easy fix. I do like the idea about adding some basic information about the parent dataset

> Also getProject() could return None so you need to handle that possibility.

I think `str(None)` just returns `"None"`. It wouldn't exactly be pretty but I think a `None` entry in any of these values would at least not break the displayed `html`

> What about pixel type and ROIs (number of ROIs) ?

I thought about ROIs but eventually refrained from adding it to restrict myself a bit to the parameters that would *always* be set for an image. But then again, there is still plenty of space in the table(s) 🤔

2024-02-01 12:21 UTC, will-moore commented on src/omero/gateway/__init__.py
> +                <td><b>Project ID: </b></td>   <td class=text-right>{self.getProject().getId()}</td>\n
If `getProject()` returns `None` then this will fail with something like `Nonetype has no attribute getId`.
Same with `self.getProject().getName()`

2024-02-01 12:33 UTC, will-moore commented
Opened PR with those changes at https://github.com/jo-mueller/omero-py/pull/1

2024-02-01 13:33 UTC, jo-mueller commented on src/omero/gateway/__init__.py
> +                <td><b>Project ID: </b></td>   <td class=text-right>{self.getProject().getId()}</td>\n
Ah, I get it! Will fix it asap.

2024-02-02 12:39 UTC, jo-mueller commented
Limited floating number precision makes it a bit prettier:

![Capture](https://github.com/ome/omero-py/assets/38459088/bc298fec-7394-428c-853e-3b796086edc2)

2024-02-02 12:44 UTC, will-moore approved these changes
Looks great, thanks

2024-02-02 13:07 UTC, jo-mueller commented
Cool! Let me know if I should change anything - I probably won't have so much time to work on it because I'll be on leave for a few months soon 👍

2024-04-11 10:04 UTC, jo-mueller commented
@will-moore @pwalczysko is there anything I should add to this PR to see it through? Happy for any feedback 👍

2024-04-11 10:37 UTC, will-moore commented
Hi @jo-mueller - apologies for dropping this.
I'd like to get a second opinion from someone on the OME team e.g. @jburel but in the meantime, it occurred to me that it might be nicer not to add all this html into the main `gateway.__init__.py` since it's already getting very verbose. Instead, the bulk of it could be moved to e.g. `omero.gateway.utils` as an `image_to_html(image)` method.

Also, in order to accept external contributions to any of the OME's GPL repos, we need to ask that you fill out a CLA form and submit it as described at https://ome-contributing.readthedocs.io/en/latest/cla.html

Thanks

2024-04-11 13:40 UTC, will-moore commented
Thanks for the CLA.

I would add the code to https://github.com/ome/omero-py/blob/master/src/omero/gateway/utils.py
e.g.

```
import base64

...

def image_repr_html(image):
    ...

   table_imageinfo = f"""
        <table>
            <tr><th></th><th>ID</th><th>Name</th></tr>
            {obj_html(image, 'Image')}
            {obj_html(image.getParent(), 'Dataset')}
            {obj_html(image.getProject(), 'Project')}
        </table>
        """
    ...

    return html
```

Then add `image_repr_html` to the imports at
https://github.com/ome/omero-py/blob/master/src/omero/gateway/__init__.py#L32

Then...
```
def _repr_html_(self):

    return image_repr_html(self)
```

2024-04-15 06:25 UTC, jo-mueller commented
Done in da9d6443549e8353ba3cd8c5aa4c952dca95620e

2024-04-16 11:25 UTC, will-moore commented
Final test with this branch installed locally, looking good...

![Screenshot 2024-04-16 at 12 24 33](https://github.com/ome/omero-py/assets/900055/585369ad-4532-4e47-a199-ba53f6081476)

2024-04-16 11:50 UTC, pwalczysko commented
With an image which does have pixelsizes, I have success

![Screenshot 2024-04-16 at 12 49 03](https://github.com/ome/omero-py/assets/2478303/b879e63a-9734-4b6a-9752-ef04b3b4bf8d)



But with an image which does not have pixelsizes, I do get an error (image created by ``touch a.fake`` cmd):

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/opt/anaconda3/envs/jotest/lib/python3.9/site-packages/IPython/core/formatters.py:344, in BaseFormatter.__call__(self, obj)
    342     method = get_real_method(obj, self.print_method)
    343     if method is not None:
--> 344         return method()
    345     return None
    346 else:

File ~/Work/omero-py/target/omero/gateway/__init__.py:299, in BlitzObjectWrapper._repr_html_(self)
    294 def _repr_html_(self):
    295     """
    296     Returns an HTML representation of the object. This is used by the
    297     IPython notebook to display the object in a cell.
    298     """
--> 299     return image_to_html(self)

File ~/Work/omero-py/target/omero/gateway/utils.py:276, in image_to_html(image)
    269 encoded_image = base64.b64encode(image.getThumbnail()).decode('utf-8')
    270 dimensions = f"""(
    271     {image.getSizeT()},
    272     {image.getSizeC()},
    273     {image.getSizeZ()},
    274     {image.getSizeY()},
    275     {image.getSizeX()})"""
--> 276 physical_dims = """({:.3f}, {:.3f}, {:.3f})""".format(
    277     image.getPixelSizeZ(),
    278     image.getPixelSizeY(),
    279     image.getPixelSizeX())
    280 physical_units = f"""(
    281     {image.getPixelSizeZ(units=True).getUnit()},
    282     {image.getPixelSizeY(units=True).getUnit()},
    283     {image.getPixelSizeX(units=True).getUnit()})"""
    285 table_dimensions = f"""
    286 <table>\n
    287     <tr>\n
   (...)
    299 </table>
    300 """

TypeError: unsupported format string passed to NoneType.__format__
```

2024-04-16 11:51 UTC, pwalczysko requested changes
Please address the image with no pixelsizes problem ^^^ thank you.

2024-04-18 07:39 UTC, jo-mueller commented
Hi @pwalczysko , 

thanks for the review, good catch!

I added some code to escape this error if the properties haven't been set (b0a7fada46d8af0764eeb94882474a610fbadde4). In this case, I would now get this:

![capture](https://github.com/ome/omero-py/assets/38459088/3525e7fe-1d39-4e6f-9a5d-abf53ca967c0)

2024-04-19 13:10 UTC, pwalczysko approved these changes

2024-04-24 09:21 UTC, merged